apiVersion: helm.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: local-provider-config
spec:
  credentials:
    source: Secret
    secretRef:
      name: local-cluster
      namespace: crossplane-system
      key: kubeconfig