apiVersion: storage.example.org/v1alpha1
kind: Bucket
metadata:
  name: {{ .Values.bucketName }}
  namespace: {{ .Values.namespace | default "default" | quote }}
spec:
  parameters:
    name: {{ .Values.bucketName }}
  compositionSelector:
    matchLabels:
      provider: aws
  writeConnectionSecretToRef:
    name: {{ .Values.s3Secret }}
    namespace: {{ .Values.namespace | default "default" | quote }}
{{ if .Values.externalCache }}
---
apiVersion: cache.example.org/v1alpha1
kind: RedisCluster
metadata:
  name: my-redis
  namespace: {{ .Values.namespace | default "default" | quote }}
spec:
  compositionSelector:
    matchLabels:
      provider: aws
  writeConnectionSecretToRef:
    name: {{ .Values.redisSecret }}
    namespace: {{ .Values.namespace | default "default" | quote }}
{{ end }}
---
apiVersion: database.example.org/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: my-db
  namespace: {{ .Values.namespace | default "default" | quote }}
spec:
  parameters:
    storageGB: 10
  compositionSelector:
    matchLabels:
      provider: aws
  writeConnectionSecretToRef:
    name: {{ .Values.postgresSecret }}
    namespace: {{ .Values.namespace | default "default" | quote }}
