apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: postgresqlinstances.database.example.org
spec:
  connectionSecretKeys:
    - database-username
    - database-password
    - database-root-password
    - database-name
    - database-server
    - port
  group: database.example.org
  names:
    kind: PostgreSQLInstance
    listKind: PostgreSQLInstanceList
    plural: postgresqlinstances
    singular: postgresqlinstance
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                storageGB:
                  type: integer
                region:
                  type: string
              required:
                - storageGB
                - region
