---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: CompositeResourceDefinition
metadata:
  name: redisclusters.cache.example.org
spec:
  connectionSecretKeys:
    - hostname
    - port
  crdSpecTemplate:
    group: cache.example.org
    version: v1alpha1
    names:
      kind: RedisCluster
      listKind: RedisClusterList
      plural: redisclusters
      singular: rediscluster
    validation:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
metadata:
  name: vpcredisclusters.aws.cache.example.org
  labels:
    provider: aws
    guide: quickstart
    vpc: {{ .Values.vpcId }}
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  reclaimPolicy: Delete
  compositeTypeRef:
    apiVersion: cache.example.org/v1alpha1
    kind: RedisCluster
  resources:
    - base:
        apiVersion: cache.aws.crossplane.io/v1alpha1
        kind: CacheSubnetGroup
        metadata:
          namespace: {{ .Values.namespace | default "default" | quote }}
        spec:
          forProvider:
            description: An excellent formation of subnetworks.
            subnetIdSelector:
              matchLabels:
                desc: quay
          providerConfigRef:
            name: aws-provider
          reclaimPolicy: Delete
    - base:
        apiVersion: cache.aws.crossplane.io/v1beta1
        kind: ReplicationGroup
        metadata:
          namespace: {{ .Values.namespace | default "default" | quote }}
        spec:
          forProvider:
            cacheNodeType: cache.t3.medium
            applyModificationsImmediately: true
            engine: redis
            replicationGroupDescription: redis cluster for Quay
            cacheSubnetGroupNameSelector:
              matchControllerRef: true
            securityGroupIdSelector:
              matchLabels:
                desc: quay
          writeConnectionSecretToRef:
            namespace: crossplane-system
            name: redis-internal-secret
          providerConfigRef:
            name: aws-provider
          reclaimPolicy: Delete
      connectionDetails:
        - name: hostname
          fromConnectionSecretKey: endpoint
        - fromConnectionSecretKey: port
      patches:
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-redis"