---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: CompositeResourceDefinition
metadata:
  name: networkgroups.ec2.example.org
spec:
  crdSpecTemplate:
    group: ec2.example.org
    version: v1alpha1
    names:
      kind: NetworkGroup
      listKind: NetworkGroupList
      plural: networkgroups
      singular: networkgroup
    validation:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
metadata:
  name: vpcnetworkgroups.aws.ec2.example.org
  labels:
    provider: aws
    guide: quickstart
    vpc: {{ .Values.vpcId }}
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  reclaimPolicy: Delete
  compositeTypeRef:
    apiVersion: ec2.example.org/v1alpha1
    kind: NetworkGroup
  resources:
    {{ if not .Values.vpcId }}
    - base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: VPC
        metadata:
          namespace: {{ .Values.namespace | default "default" | quote }}
          labels:
            desc: quay
        spec:
          forProvider:
            cidrBlock: 10.0.0.0/16
            enableDnsHostNames: true
            enableDnsSupport: true
          providerConfigRef:
            name: aws-provider
          reclaimPolicy: Delete
    {{ end }}
    {{ if not .Values.igwId }}
    - base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: InternetGateway
        metadata:
          namespace: {{ .Values.namespace | default "default" | quote }}
          labels:
            desc: quay
        spec:
          forProvider:
            {{ if .Values.vpcId }}
            vpcId: {{ .Values.vpcId }}
            {{ else }}
            vpcIdSelector:
              matchLabels:
                desc: quay
            {{ end }}
          providerConfigRef:
            name: aws-provider
          reclaimPolicy: Delete
    {{ end }}
    - base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: Subnet
        metadata:
          namespace: {{ .Values.namespace | default "default" | quote }}
          labels:
            desc: quay
            zone: {{ printf "%sa" .Values.region }}
        spec:
          forProvider:
            cidrBlock: {{ .Values.aZCIDRa }}
            {{ if .Values.vpcId }}
            vpcId: {{ .Values.vpcId }}
            {{ else }}
            vpcIdSelector:
              matchLabels:
                desc: quay
            {{ end }}
            availabilityZone: {{ printf "%sa" .Values.region }}
          providerConfigRef:
            name: aws-provider
          reclaimPolicy: Delete
    - base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: Subnet
        metadata:
          namespace: {{ .Values.namespace | default "default" | quote }}
          labels:
            desc: quay
            zone: {{ printf "%sb" .Values.region }}
        spec:
          forProvider:
            cidrBlock: {{ .Values.aZCIDRb }}
            {{ if .Values.vpcId }}
            vpcId: {{ .Values.vpcId }}
            {{ else }}
            vpcIdSelector:
              matchLabels:
                desc: quay
            {{ end }}
            availabilityZone: {{ printf "%sb" .Values.region }}
          providerConfigRef:
            name: aws-provider
          reclaimPolicy: Delete
    - base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: Subnet
        metadata:
          namespace: {{ .Values.namespace | default "default" | quote }}
          labels:
            desc: quay
            zone: {{ printf "%sc" .Values.region }}
        spec:
          forProvider:
            cidrBlock: {{ .Values.aZCIDRc }}
            {{ if .Values.vpcId }}
            vpcId: {{ .Values.vpcId }}
            {{ else }}
            vpcIdSelector:
              matchLabels:
                desc: quay
            {{ end }}
            availabilityZone: {{ printf "%sc" .Values.region }}
          providerConfigRef:
            name: aws-provider
          reclaimPolicy: Delete
    - base:
        apiVersion: ec2.aws.crossplane.io/v1alpha4
        kind: RouteTable
        metadata:
          namespace: {{ .Values.namespace | default "default" | quote }}
        spec:
          forProvider:
            {{ if .Values.vpcId }}
            vpcId: {{ .Values.vpcId }}
            {{ else }}
            vpcIdSelector:
              matchLabels:
                desc: quay
            {{ end }}
            routes:
              - destinationCidrBlock: 0.0.0.0/0
                {{ if .Values.igwId }}
                gatewayId: {{ .Values.igwId }}
                {{ else }}
                gatewayIdSelector:
                  matchLabels:
                    desc: quay
                {{ end }}
            associations:
              - subnetIdSelector:
                  matchLabels:
                    desc: quay
                    zone: {{ printf "%sa" .Values.region }}
              - subnetIdSelector:
                  matchLabels:
                    desc: quay
                    zone: {{ printf "%sb" .Values.region }}
              - subnetIdSelector:
                  matchLabels:
                    desc: quay
                    zone: {{ printf "%sc" .Values.region }}
          providerConfigRef:
            name: aws-provider
          reclaimPolicy: Delete
    - base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: SecurityGroup
        metadata:
          namespace: {{ .Values.namespace | default "default" | quote }}
          labels:
            desc: quay
        spec:
          forProvider:
            {{ if .Values.vpcId }}
            vpcId: {{ .Values.vpcId }}
            {{ else }}
            vpcIdSelector:
              matchLabels:
                desc: quay
            {{ end }}
            groupName: crossplane-quay
            description: Allow access to Quay dependencies
            ingress:
            - fromPort: 6379
              toPort: 6379
              ipProtocol: tcp
              ipRanges:
              - cidrIp: 0.0.0.0/0
                description: Everywhere
            - fromPort: 5432
              toPort: 5432
              ipProtocol: tcp
              ipRanges:
              - cidrIp: 0.0.0.0/0
                description: Everywhere
            egress:
            - fromPort: 6379
              toPort: 6379
              ipProtocol: tcp
              ipRanges:
              - cidrIp: 0.0.0.0/0
                description: Everywhere
            - fromPort: 5432
              toPort: 5432
              ipProtocol: tcp
              ipRanges:
              - cidrIp: 0.0.0.0/0
                description: Everywhere
          providerConfigRef:
            name: aws-provider
          reclaimPolicy: Delete
