apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
metadata:
  name: buckets.aws.storage.example.org
  labels:
    provider: aws
    guide: quickstart
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  reclaimPolicy: Delete
  compositeTypeRef:
    apiVersion: storage.example.org/v1alpha1
    kind: Bucket
  resources:
    - base:
        apiVersion: identity.aws.crossplane.io/v1alpha1
        kind: IAMUser
        metadata: {}
        spec:
          forProvider: {}
          providerConfigRef:
            name: aws-provider
          deletionPolicy: Delete
      patches:
      - fromFieldPath: spec.userName
        toFieldPath: metadata.name
    - base:
        apiVersion: identity.aws.crossplane.io/v1alpha1
        kind: IAMAccessKey
        metadata: 
          name: iamaccesskey
        spec:
          forProvider:
            userNameSelector:
              matchControllerRef: true
          providerConfigRef:
            name: aws-provider
          deletionPolicy: Delete
      patches:
        - fromFieldPath: spec.userName
          toFieldPath: metadata.name 
          transforms:
            - type: string
              string:
                fmt: "accesskey-%s"
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-user"
      connectionDetails:
        - name: accessKey
          fromConnectionSecretKey: username
        - name: secretKey
          fromConnectionSecretKey: password
    - base:
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        metadata: {}
        spec:
          forProvider:
            acl: private
          writeConnectionSecretToRef: 
            namespace: crossplane-system
            name: bucket-internal-secret
          providerConfigRef:
            name: aws-provider
          deletionPolicy: Delete
      patches:
        - fromFieldPath: "spec.bucketName"
          toFieldPath: "metadata.name"
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.locationConstraint"
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-bucket"
      connectionDetails:
        - name: host
          fromConnectionSecretKey: endpoint
    - base:
        apiVersion: s3.aws.crossplane.io/v1alpha1
        kind: BucketPolicy
        metadata:
          name: bucketPolicy
        spec:
          forProvider:
            bucketNameSelector: 
              matchControllerRef: true
            statement:
              - action:
                  - s3:ListBucket
                  - s3:GetBucketLocation
                  - s3:ListBucketMultipartUploads
                  - s3:PutBucketCORS
                effect: Allow
                principal:
                  awsPrincipals:
                    - iamUserArnSelector:
                        matchControllerRef: true
                resource:
                  - quay.demo.octo.redhat.com
              - effect: Allow
                action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                  - s3:ListMultipartUploadParts
                  - s3:AbortMultipartUpload
                principal:
                  awsPrincipals:
                    - iamUserArnSelector:
                        matchControllerRef: true
                resource:
                  - quay.demo.octo.redhat.com
            version: '2012-10-17'
            name: aws-provider
          reclaimPolicy: Delete
          providerConfigRef:
            name: aws-provider
      patches:
        - fromFieldPath: "spec.bucketName"
          toFieldPath: "metadata.name"
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.statement[0].resource[0]"
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.statement[1].resource[0]"