apiVersion: apiextensions.crossplane.io/v1alpha1
kind: CompositeResourceDefinition
metadata:
  name: buckets.storage.example.org
spec:
  connectionSecretKeys:
    - secretKey
    - accessKey
    - host
  group: storage.example.org
  names:
    kind: Bucket
    listKind: BucketList
    plural: buckets
    singular: bucket
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                bucketName:
                  type: string
                userName:
                  type: string
                region:
                  type: string
              required:
                - bucketName
                - userName
                - region